### ISSUE TITLE
[v1.0.0] Crash on load

### ISSUE THREAD

**Issue by Luke616** [abused/Technomancy-2#1]
Minecraft v. 1.12.2
Forge v. 14.23.2.2623
Technomancy v. 1.0.0

Here is the link, which should contain a modlist:
https://pastebin.com/hyEcfMqa

**Comment by alothmanmoe** [comment]
Hello! Thank you for reporting the issue, the mod is still heavily in alpha and there are some things that i'm not able to catch, i'll have a fix out for this in just a bit!

**Comment by alothmanmoe** [comment]
This should now be fixed in version 1.0.1, it's posted on curse awaiting curse approval, should approved within the next few hours
